//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dundes.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     133
#define IDC_NUMBER                      1000
#define IDC_VALUE                       1001
#define ID_ITEMS_WALL                   32771
#define ID_ITEMS_DOOR                   32772
#define ID_ITEMS_MONSTER                32773
#define ID_ITEMS_TREASURE               32774
#define ID_ITEMS_KEY                    32775
#define ID_ITEMS_SWORD                  32776
#define ID_ITEMS_ARMOR                  32777
#define ID_ITEMS_POTION                 32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
